version: 0.2
phases:
  pre_build:
    commands:
      - echo intalling terraform 
      - apt update && apt install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt update && apt install terraform
      - echo verifying installation
      - terraform -help
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: imagedefinitions.json