version: 0.2
phases:
  pre_build:
    commands:
      - echo intalling terraform 
      - apt update && apt install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - apt install zip -y
      - unzip terraform*.zip
      - sudo mv terraform /usr/local/bin
      - echo verifying installation
      - terraform version
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: imagedefinitions.json