version: 0.2

env:
phases:
  install:
    commands:
      - echo intalling terraform 
      - apt update && sudo apt-get install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
      - echo Starting pre-build...
      - ls -ls
      - source ${BASE_PATH}/prebuild.sh
  build:
    commands:
      - ./${BASE_PATH}/test.sh