version: 0.2
phases:
  pre_build:
    commands:
      - echo intalling terraform 
      - wget https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
      - apt install zip -y
      - unzip terraform*.zip
      - mv terraform /usr/local/bin
      - echo verifying installation
      - terraform version
  build:
    commands:
      - echo initializing terraform
      - terraform init
      - echo check change plan
      - terraform plan
      - terraform destroy -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: imagedefinitions.json