version: 0.2

env:
  variables:
    ENVIRONMENT: int
    TF_IN_AUTOMATION: 1
    TERRAFORM_VERSION: 0.13.4
    BASE_PATH: modules/codepipeline

phases:
  install:
    runtime-versions:
      golang: 1.14
      python: 3.8
    commands:
      - ./${BASE_PATH}/install.sh
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
      - echo Starting pre-build...
      - ls -ls
      - source ${BASE_PATH}/prebuild.sh
  build:
    commands:
      - ./${BASE_PATH}/test.sh